name: Deploy Vercel
on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: amondnet/vercel-action@v20
        id: vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          alias-domains:  |
            faststore.sanderpaniago.dev
            pr-{{PR_NUMBER}}.sanderpaniago.dev
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn --silent && yarn global add @lhci/cli@0.6.x

      - run: yarn build
      - run: lhci autorun
        env:
          BASE_SITE_URL: ${{ steps.vercel.outputs.preview-url }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
